name: Playwright Tests

# IMPORTANT: Move the .github folder to repo root and fix the WORKDIR env. variable

env:
  WORKDIR: ./

# Change the trigger to run on each push
on: workflow_dispatch
  # push:
  #   branches: [ main, master ]
  # pull_request:
  #   branches: [ main, master ]

# Permissions needed to publish test results
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

# All the jobs
jobs:
  test:
    name: 'Run tests and publish results'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
      working-directory: $WORKDIR
    - name: Install Playwright Browsers
      working-directory: $WORKDIR
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      working-directory: $WORKDIR
      # increase levels here, for instance -g "L[0-2]\s"
      run: npx playwright test -g "L[0]\s"
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: $WORKDIR/playwright-report/test-results.xml
        retention-days: 30
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          $WORKDIR/playwright-report/test-results.xml
